"""Linear Algebra answer-equivalence corpus.

Generated by a different model than the one that wrote grading.py, and never
shown to it while it implemented. That independence is the point: an
implementation passing tests its own author wrote proves much less.

Cases known to fail today are marked xfail with the reason, so the suite stays
green and any fix shows up as XPASS rather than needing the list re-edited.
"""

from __future__ import annotations

import pytest

from grading import grade_problem_answer

# (id, student_answer, expected_answer, should_match)
EQUIVALENT = [
    ("eq_01", "1/8", "0.125"),
    ("eq_02", "5/2", "2.5"),
    ("eq_03", "-1/3", "-0.333333333333333"),
    ("eq_04", "[[0, 1], [-1, 0]]", "[[0,1],[-1,0]]"),
    ("eq_05", "[ [ 1, 0 ], [ 0, 1 ] ]", "[[1,0],[0,1]]"),
    ("eq_06", "[1, 2; 3, 4]", "[[1, 2], [3, 4]]"),
    ("eq_07", "(4, 5, 6)", "<4,5,6>"),
    ("eq_08", "[7 8 9]", "(7, 8, 9)"),
    ("eq_09", "<-1, 0, 1>", "[-1, 0, 1]"),
    ("eq_10", "y = 10", "10"),
    ("eq_11", "det(A) = -5", "-5"),
    ("eq_12", "v = (1, 1)", "(1, 1)"),
    ("eq_13", "sqrt(5)", "2.236067977"),
    ("eq_14", "3sqrt(2)", "4.242640687"),
    ("eq_15", "sqrt(3)/2", "0.866025403"),
    ("eq_16", "{-1, 0, 1}", "{1, 0, -1}"),
    ("eq_17", "{2, 2, 3}", "{3, 2, 2}"),
    ("eq_18", "{lambda = 5, 1}", "{1, 5}"),
    ("eq_19", "y = -3t", "-3t"),
    ("eq_20", "t(1, -1, 0)", "(t, -t, 0)"),
    ("eq_21", "s(2, 4) + t(1, 1)", "(2s+t, 4s+t)"),
    ("eq_22", "rank = 2", "2"),
    ("eq_23", "4.0", "4"),
    ("eq_24", "-0", "0"),
    ("eq_25", "3+4i", "3 + 4i"),
    ("eq_26", "-1-i", "-1 - 1i"),
    ("eq_27", "2+isqrt(3)", "2 + 1.73205081i"),
    ("eq_28", "[[1, 0 | 5], [0, 1 | -2]]", "[[1, 0, 5], [0, 1, -2]]"),
    ("eq_29", "A^T = [[1, 3], [2, 4]]", "[[1, 3], [2, 4]]"),
    ("eq_30", "x = 1, y = 2", "(1, 2)"),
]

# A wrong answer accepted is far worse than a right answer rejected: it trains
# the wrong recall. None of these may ever pass.
NON_EQUIVALENT = [
    ("ne_01", "[[1, 2], [3, 4]]", "[[1, 3], [2, 4]]"),
    ("ne_02", "(1, 2, 3)", "(2, 1, 3)"),
    ("ne_03", "0.125", "0.126"),
    ("ne_04", "-5", "5"),
    ("ne_05", "2/3", "3/5"),
    ("ne_06", "{1, 2, 3}", "{1, 2}"),
    ("ne_07", "3+4i", "3-4i"),
    ("ne_08", "sqrt(2)", "sqrt(3)"),
    ("ne_09", "[[1, 2, 3], [4, 5, 6]]", "[[1, 4], [2, 5], [3, 6]]"),
    ("ne_10", "(5, 5)", "5"),
]

# Known gaps, measured 2026-08-19 against commit bbb22a1.
KNOWN_GAPS = {
    "eq_18": "labelled element inside a set literal is not parsed",
    "eq_20": "needs the symbolic tier; sympy is not installed",
    "eq_21": "needs the symbolic tier; sympy is not installed",
    "eq_30": "component-wise assignment is not read as a tuple",
}


def _case(entry):
    case_id = entry[0]
    marks = []
    if case_id in KNOWN_GAPS:
        marks.append(pytest.mark.xfail(reason=KNOWN_GAPS[case_id], strict=False))
    return pytest.param(*entry, id=case_id, marks=marks)


@pytest.mark.parametrize("case_id,student,expected", [_case(e) for e in EQUIVALENT])
def test_equivalent_answers_are_accepted(case_id, student, expected):
    assert grade_problem_answer(student, expected), (
        f"{case_id}: {student!r} is mathematically equal to {expected!r} but was graded wrong"
    )


@pytest.mark.parametrize("case_id,student,expected", [_case(e) for e in NON_EQUIVALENT])
def test_non_equivalent_answers_are_rejected(case_id, student, expected):
    assert not grade_problem_answer(student, expected), (
        f"{case_id}: {student!r} is NOT equal to {expected!r} but was graded correct"
    )
